finalarm_position_controller_1:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint_1
    joint_speed: 0.5
    joint_compliance_margin: 1
    joint_compliance_slope: 4
    motor:
        id: 1
        init: 2048
        min: 0
        max: 4096
        bias: 0.39269908169 #-0.528617013529 #-0.608617013529

finalarm_position_controller_2:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint_2
    joint_speed: 0.5
    joint_compliance_margin: 1
    joint_compliance_slope: 4
    motor:
        id: 2
        init: 2048
        min: 0
        max: 4096
        bias: 0 #-0.160377691373

finalarm_position_controller_3:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint_3
    joint_speed: 0.5
    motor:
        id: 3
        init: 2048
        min: 0
        max: 4096

finalarm_position_controller_4:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint_4
    joint_speed: 0.5
    joint_compliance_margin: 1
    joint_compliance_slope: 4
    motor:
        id: 4
        init: 2048
        min: 0
        max: 4096

finalarm_position_controller_5:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint_5
    joint_speed: 0.5
    motor:
        id: 5
        init: 2048
        min: 0
        max: 4096

finalarm_position_controller_6:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint_6
    joint_speed: 1.0
    motor:
        id: 6
        init: 2048
        min: 0
        max: 4096
        bias: 0

finalarm_position_controller_7:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint_7
    joint_speed: 3.0
    motor:
        id: 7
        init: 2048
        min: 0
        max: 4096

finalarm_position_controller_8:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint_8
    joint_speed: 0.5
    joint_torque_limit: 1.0
    motor:
        id: 8
        init: 512
        min: 0 #400
        max: 1023 #611

finalarm_position_controller_9:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint_9
    joint_speed: 0.5
    joint_torque_limit: 1.0
    motor:
        id: 9
        init: 512
        min: 0 #400
        max: 1023 #611

finalarm_joint_trajectory_action_controller:
    controller:
        package: dynamixel_controllers
        module: joint_trajectory_action_controller
        type: JointTrajectoryActionController
    joint_trajectory_action_node:
        min_velocity: 0.5
        constraints:
            goal_time: 5.0
